// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknALXJ2W7a9Bk1bh2f6ZyJTNJewALcfw',
    appId: '1:713325574307:web:5cbff754bf98095b626716',
    messagingSenderId: '713325574307',
    projectId: 'bigtalk-468f9',
    authDomain: 'bigtalk-468f9.firebaseapp.com',
    storageBucket: 'bigtalk-468f9.appspot.com',
    measurementId: 'G-NCX0QBQNB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvdT6NksL0H4GbkHD816mh1nTvyq3VOCo',
    appId: '1:713325574307:android:9e216e5e4f8eb195626716',
    messagingSenderId: '713325574307',
    projectId: 'bigtalk-468f9',
    storageBucket: 'bigtalk-468f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV8u924KzYchTS8Yu1J8zg3FKdkCR2M5Y',
    appId: '1:713325574307:ios:421d038d4a36c43a626716',
    messagingSenderId: '713325574307',
    projectId: 'bigtalk-468f9',
    storageBucket: 'bigtalk-468f9.appspot.com',
    iosBundleId: 'com.example.ivywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV8u924KzYchTS8Yu1J8zg3FKdkCR2M5Y',
    appId: '1:713325574307:ios:421d038d4a36c43a626716',
    messagingSenderId: '713325574307',
    projectId: 'bigtalk-468f9',
    storageBucket: 'bigtalk-468f9.appspot.com',
    iosBundleId: 'com.example.ivywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDknALXJ2W7a9Bk1bh2f6ZyJTNJewALcfw',
    appId: '1:713325574307:web:503dfe471faf72a6626716',
    messagingSenderId: '713325574307',
    projectId: 'bigtalk-468f9',
    authDomain: 'bigtalk-468f9.firebaseapp.com',
    storageBucket: 'bigtalk-468f9.appspot.com',
    measurementId: 'G-ZT8HF9SWK0',
  );
}
